### ISSUE TITLE
Readme should clarify that this doesn't have global push-to-talk

### ISSUE THREAD

**Issue by vith** [XNBlank/discord-linux#1]
This is probably one of most common reasons a user would be looking for a desktop version of Discord, I think it's reasonable to have a note in the readme clarifying that it's not feature-equivalent to the official desktop apps.

**Comment by XNBlank** [comment]
Ah, you're right. Kind of ignorant of me, especially since I added said fact to the Discord channel and not the README. Sorry about that. Will update.
