### ISSUE TITLE
Can't you add PTT support by using a binary module?

### ISSUE THREAD

**Issue by SoniEx2** [XNBlank/discord-linux#10]
Title says it all. It's a hack but w/e.

**Comment by jacobmischka** [comment]
There are several hacky ways to add it, but none of them are all that great and they don't integrate with the actual discord settings. Just wait until the official linux release.

**Comment by XNBlank** [comment]
I've thought about it, but in the end I don't think it'd be worth it. Like jacob said, best to wait for the official linux release for that.

**Comment by vith** [comment]
I just made this: https://github.com/vith/discord-hotkey-forwarder

It doesn't work well enough to use while gaming though. :disappointed: 

The discord-linux window won't listen to key events unless it has focus, so I had to temporarily focus it, which means you'll temporarily not be able to send input to whatever you had focused before...

And Dota 2 makes the global keybind stop working while you're actually in a game (but not in the menus).

**Comment by SoniEx2** [comment]
@vith That's not the same as using a binary module to directly trigger the required JS events, bypassing the "browser"'s own handling.

**Comment by jacobmischka** [comment]
Electron itself has global hotkeys built in, neither of your solutions are
required if you really want this that badly. If you figure out what the
required events actually are it would be trivial to add.

**Comment by jacobmischka** [comment]
However you then need to add a settings menu, or figure out how to grab the settings from the internal discord webpage.

**Comment by simoniz0r** [comment]
Surely someone could make a custom hotkey that would only unmute the default microphone when pressed.  I mean at the system level, not in discord itself.  Not exactly the best solution, but it would work for the time being.  A quick google search would suggest that a few programs already exist to do this.  Here's one:
https://github.com/coddingtonbear/linux-push-to-talk

**Comment by jacobmischka** [comment]
Then use that? If it's at a system level then why would it need integration with this?

**Comment by simoniz0r** [comment]
I wasn't suggesting that you integrate it with discord-linux; this was a suggestion for the OP.

**Comment by jacobmischka** [comment]
Oh I see, my mistake

**Comment by mesmerus** [comment]
That's actually a pretty slick idea; my Roccat Kave has a mute mic button on the stand, but it makes a _tiny_ pop that people can hear if there isn't much conversation/noise going on. Having a system mute/unmute (or just volume=0/volume=normal toggle) would get around this, plus I could make it apply to all input devices, regardless of which one I'm using at the moment.

**Comment by simoniz0r** [comment]
I've been using Discord on Xubuntu for about a month now.  I found this command that you can assign to a keyboard shortcut to toggle mic muting.  I've been using it, and it works perfectly.

```
pactl set-source-mute  $(pacmd list-sources|awk '/\* index:/{ print $3 }') toggle
```
