### ISSUE TITLE
X-Frame-Options error on latest source release

### ISSUE THREAD

**Issue by JesseFarebro** [XNBlank/discord-linux#14]
I'm still receiving the X-Frame-Options error on the latest release which I just downloaded. Is there anything else I should be aware of?

The log states:

```
[23205:1213/213952:INFO:CONSOLE(0)] "Refused to display 'https://discordapp.com/channels/@me' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.", source: about:blank (0)
```

**Comment by jacobmischka** [comment]
Yeah, don't use the source releases. Download one of the newer tags that are incorrectly tagged as AUR. 

https://github.com/XNBlank/discord-linux/releases/tag/x86-0.1.3-AUR

https://github.com/XNBlank/discord-linux/releases/tag/x64-0.1.3-AUR

The newest release has updated binaries but outdated source, these tags have the new source, albeit with an erroneous tag. Next release shouldn't have this issue.

**Comment by JesseFarebro** [comment]
Excellent, that solves everything!
