### ISSUE TITLE
No permission to access microphone

### ISSUE THREAD

**Issue by konomikitten** [XNBlank/discord-linux#15]
Seems the app has no permission to access the microphone and I can find no way to give it access to the microphone because of the wrapper. Any solutions?

**Comment by jacobmischka** [comment]
I'm pretty sure there's an option you can click in the settings that gives it to you. I would check but the site seems to be down right now as I'm getting a cloudflare page when I try to open the app. I'll check back later.

**Comment by konomikitten** [comment]
@jacobmischka yeah it's down at the moment (I can't chat with my friends! _meh_) anyway there's no setting I can find in the Discord Website itself, and I'm sure it's talking about telling the browser to give permission, but in this case since the browser interface is hidden I am unable to do so.

**Comment by jacobmischka** [comment]
Yeah, just click the "access to your microphone" link and it should automatically give you permissions. 

![image](https://cloud.githubusercontent.com/assets/3939997/12036462/bce2ccde-ae0b-11e5-9bdc-0bdc82529de0.png)

**Comment by konomikitten** [comment]
Case of user error I didn't know it was clickable thanks!
