### ISSUE TITLE
No tarball for x86

### ISSUE THREAD

**Issue by rockneurotiko** [XNBlank/discord-linux#19]
Hi!

I'm updating the AUR version for 0.1.4 and there are no link for the x86 version ([I'm trying this](https://github.com/XNBlank/discord-linux/archive/x86-0.1.4.tar.gz)).

Thanks :)

**Comment by jacobmischka** [comment]
I've created a 32 bit branch here https://github.com/jacobmischka/discord-linux/tree/x86, as far as I know there's not a way for me to submit a pull request to make a new branch so we'll need @XNBlank to manually create it.

Only three files are different between the two architectures:
- The electron (discord) binary
- libnode.so
- snapshot_blob.bin

**Comment by XNBlank** [comment]
@jacobmischka I don't know why I didn't think of that. Created the branch.
https://github.com/XNBlank/discord-linux/tree/x86
