### ISSUE TITLE
Unable to install on Ubuntu 15.04 32bit system

### ISSUE THREAD

**Issue by RPiAwesomeness** [XNBlank/discord-linux#2]
I downloaded the 32 bit .deb file and tried to install via `sudo dpkg -i discordlinux_0.1-1-ia32.deb`.

However I got this error:
![selection_031](https://cloud.githubusercontent.com/assets/11481499/10128129/1370be68-657c-11e5-9c72-80cc98582ec0.png)

Can you fix this, or do I need to compile it myself?

**Comment by XNBlank** [comment]
This is my bad. I packaged the deb for the 32bit systems incorrectly. I will upload a fix asap.

**Comment by XNBlank** [comment]
Sorry about that. The fixed .deb has been uploaded. Please redownload and try it now. If it works let me know here.

**Comment by RPiAwesomeness** [comment]
Works great! :) :+1:
