### ISSUE TITLE
Drag and drop image replaces discord with image

### ISSUE THREAD

**Issue by ghost** [XNBlank/discord-linux#21]
Using Manjaro, if an image is dragged into a conversation it replaces discord with the picture of the image, like a browser would if you drag in image into a tab.

**Comment by sunshinehunter** [comment]
It's not limited to just pictures, also to every other file, like text files (will open) or jar files (will download)

**Comment by jacobmischka** [comment]
This seems to be a chromium bug: https://code.google.com/p/chromium/issues/detail?id=412373

There's a workaround mentioned there and on a related electron issue (https://github.com/atom/electron/issues/1276), I'll look into it at some point tonight and see if it works.

**Comment by jacobmischka** [comment]
I lied, that wasn't the problem. This issue was fixed in https://github.com/atom/electron/pull/931, and should be fixed in this package with #23.
