### ISSUE TITLE
Version 0.1-4 won't launch on Xubuntu

### ISSUE THREAD

**Issue by simoniz0r** [XNBlank/discord-linux#22]
I installed version 0.1-3 using the .deb file, and it launches fine.  I launched the archive manager as root and extracted version 0.1-4 to the directory where 0.1-3 was installed (/usr/local/bin/discord-linux-x64).  After doing this, Discord-linux no longer launches.  Attempting to launch it through the terminal reveals this error:

```
error while loading shared libraries: libnotify.so.4: wrong ELF class: ELFCLASS64
```

Thanks in advance for any help.

**Comment by XNBlank** [comment]
The app is trying to load a 64bit library. I'm assuming you downloaded the x86 version. Did you download the correct version architecture for your computer?

**Comment by simoniz0r** [comment]
Sure didn't.  The download was a bit confusing.. I think you might have mislabeled the most recent version; they both say (64-Bit). 

Linux x86 Release (64Bit) 0.1-4
Linux x64 Release (64Bit) 0.1-4

It's working now that I installed the correct version.  Thanks.

**Comment by XNBlank** [comment]
My bad. Sorry for the confusion.
