### ISSUE TITLE
Drag and drop members

### ISSUE THREAD

**Issue by surdaft** [XNBlank/discord-linux#24]
There seems to be an issue with dragging and dropping users between channels (As well as reordering channels), but only when using this wrapper. Would this be something that could potentially be worked around or is it just how the electron wrapper works which prevents the drag and drop from completing?

**Comment by XNBlank** [comment]
I'm not having issues with dragging members around. What distro and DE are you using?

**Comment by surdaft** [comment]
I am using Ubuntu 15.10, I'm sorry what do you mean DE?

**Comment by jacobmischka** [comment]
DE means desktop environment, and it would be Unity in your case on Ubuntu unless you changed it. 

I also seem to be unable to reorder channels, I'll look into it soon.

**Comment by jacobmischka** [comment]
I'm _pretty_ sure this is related to https://github.com/atom/electron/issues/2897 and https://code.google.com/p/chromium/issues/detail?id=412373. 

I'm not exactly sure how to go about applying the given workaround, nor am I sure if it's even possible given discord's various levels of obfuscation.

**Comment by surdaft** [comment]
Hmm that's not good, oh well.. I guess it's time to close the issue if we can't do anything about it right now. Thank you for looking into it

**Comment by jacobmischka** [comment]
It might not be that bad, I've asked for clarification elsewhere so maybe it'll be relatively easy. We'll see.
