### ISSUE TITLE
Black screen when certain characters are on screen

### ISSUE THREAD

**Issue by snipeytje** [XNBlank/discord-linux#26]
When using the wrapper and certain characters appear the screen goes black and nothing responds until refreshing

Characters that will cause this problem:
- 🚀
- 🎵
- and more because I have not been able to find a cause for all of them

**Comment by jacobmischka** [comment]
It seems to work fine for me. 
![image](https://cloud.githubusercontent.com/assets/3939997/13151717/04af90ea-d631-11e5-8753-8b1349fba707.png)

Can you run discord from the command line and see if it gives you any errors when it happens?

**Comment by snipeytje** [comment]
I get no command line output when running discord and the screen goes black

**Comment by jacobmischka** [comment]
Do you have symbola installed?

**Comment by snipeytje** [comment]
yes I can see them fine when using discord in firefox or chrome, but not in the wrapper

**Comment by XNBlank** [comment]
Can't seem to reproduce this either. What distro are you using?

**Comment by snipeytje** [comment]
I'm on Arch

**Comment by jacobmischka** [comment]
So am I

**Comment by XNBlank** [comment]
Hi. Some of the community members have been able to solve this issue before we got to it. What I believe you're missing is freetype-font. They've come to the conclusion that freetype2-infinality or freetype2-ubuntu should solve your issue.

Both should be on the AUR. Try installing one of those and see if it fixes the issue.

**Comment by snipeytje** [comment]
that did indeed fix the issue for me

**Comment by Limdel** [comment]
just correcting. it's not a font, it's rendering library.

**Comment by gourdcaptain** [comment]
Is there any other way to fix this? Infinality causes eye strain for me.

**Comment by jacobmischka** [comment]
Try installing the ubuntu one. It looks better imo as well, that's why I installed it initially and why I never had this problem.
