### ISSUE TITLE
libnode.so: cannot open shared object file: No such file or directory when trying to run

### ISSUE THREAD

**Issue by piexil** [XNBlank/discord-linux#29]
I just extracted the tarball and when I go to run it I get this
`./discord: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory`

I'm on ubuntu 15.10 X64

**Comment by jacobmischka** [comment]
Do you not have libnode.so in that directory? It should be there. You're sure you downloaded the right architecture? Can you post the results of `ldd ./discord`?
