### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Silent-Hunter** [XNBlank/discord-linux#30]
I want to try to port this to the OpenPandora, and ARM based Linux handheld computer. But I cannot find the sources, is this a closed source project?

**Comment by amclay** [comment]
This is an open source project. You can read the source here: https://github.com/XNBlank/discord-linux

**Comment by jacobmischka** [comment]
The `discord` binary is literally just electron. All of the source for this project specifically is in the `resources` folder. https://github.com/XNBlank/discord-linux/tree/master/resources/app

**Comment by jacobmischka** [comment]
The source for electron is [here](https://github.com/electron/electron), anywhere electron runs this app should run.

**Comment by XNBlank** [comment]
What they said.
