### ISSUE TITLE
No desktop notification

### ISSUE THREAD

**Issue by Snaipe** [XNBlank/discord-linux#31]
The discord client for linux does not seem to notify on a new message (only a sound so far).

Distro: Archlinux
WM: xmonad

**Comment by jacobmischka** [comment]
Are you aware there's an official one now? It's in your best interest to use that one.

https://www.reddit.com/r/discordapp/comments/4bu7lm/discord_linux_very_experimental_canary_release/

**Comment by XNBlank** [comment]
Do you have libnotify?

**Comment by Snaipe** [comment]
> Do you have libnotify?

Yes. Other programs can use it fine (it highlights the relevant virtual desktop), but the client doesn't.
