### ISSUE TITLE
Add a keyboard shortcut to close application

### ISSUE THREAD

**Issue by blankoworld** [XNBlank/discord-linux#33]
Is there any keyboard shortcut that can close the application?

I tried Ctrl + Q, without any result.

It could be nice to close Discord while using Ctrl + Q.

Thanks in advance,

Olivier.

**Comment by jacobmischka** [comment]
I'm pretty sure that the standard alt+f4 works.

Also, unless you have a specific reason to continue using this app, you should use the official one linked in the README.

**Comment by blankoworld** [comment]
As I don't have any window manager, Alt+F4 doesn't work. That's why I'm talking about a Ctrl + Q shortcut.

As adviced I will try official link in the README. Thanks ;)

**Comment by jacobmischka** [comment]
Oh I see, my mistake for assuming. Hopefully the official one works out.

If it doesn't and you want to use this package instead I can submit a PR to add that shortcut. Just report back here if you'd like that.

**Comment by blankoworld** [comment]
I tried [discord-canary on ArchLinux](https://aur.archlinux.org/packages/discord-canary/), and it seems that Ctrl + Q works well on it.

So I close the ticket and hope that nobody needs this shortcut.

I really appreciate your app, so thank you having created it ;)
