### ISSUE TITLE
call audio issue

### ISSUE THREAD

**Issue by MatejBivr** [XNBlank/discord-linux#34]
during a call i can`t hear anything, my mic is working. in the settings both dropdowns are not clickable and locked to default. 
distro: fedora 24

**Comment by MatejBivr** [comment]
figured out it`s a UDP connection issue (ICE Checking message loop)

**Comment by jacobmischka** [comment]
Unless you have a reason to continue using this, I would recommend you use the [official canary package](https://www.reddit.com/r/discordapp/comments/4bu7lm/discord_linux_very_experimental_canary_release/)
