### ISSUE TITLE
Archlinux AUR package

### ISSUE THREAD

**Issue by rockneurotiko** [XNBlank/discord-linux#4]
Hi!

I created an AUR package for the discord app :smile: 

It's my first package in AUR, so maybe I'm doing something wrong, but seems that it's ok and working (at least in x86_64)

Thanks for this awesome platform!

The [AUR package](https://aur.archlinux.org/packages/discord/)

**Comment by XNBlank** [comment]
Thanks. Added to README.MD.

**Comment by skgsergio** [comment]
It works on i686, I've tested it on a VM :+1:

**Comment by rockneurotiko** [comment]
Thanks @skgsergio (and for the clean up of the PKGBUILD :smile: )
