### ISSUE TITLE
Light theme looks strange

### ISSUE THREAD

**Issue by meew0** [XNBlank/discord-linux#7]
I used discord-linux for the first time today (installed from the AUR using yaourt), and the Light theme looks like this:

![screenshot](http://i.imgur.com/zyE6WvA.png)

The dark theme looks as intended (or at least as it looks on the webapp). I'm using Antergos 2015.06 (Linux Kernel 4.1.6-1) on an Intel i7 4790k (GPU is a GTX 970). Am I doing something wrong?

**Comment by jacobmischka** [comment]
This was fixed in 3084039961f8c6a1635efe94411bee0440620556. The binaries/aur PKGBUILD haven't been updated yet, however.

**Comment by jacobmischka** [comment]
Luckily this is pretty easy to fix for the meantime. Just `sudo vim /opt/discord/resources/app/index.html` and replace those two lines.

**Comment by XNBlank** [comment]
This has been resolved and will be fixed in the next update push.
